import type { Theme } from './types';

import darkModern from './themes/dark-modern.json';
import lightModern from './themes/light-modern.json';
import midnightViolet from './themes/midnight-violet.json';
import nordic from './themes/nordic.json';
import solarDusk from './themes/solar-dusk.json';
import solarDawn from './themes/solar-dawn.json';
import forest from './themes/forest.json';
import crimson from './themes/crimson.json';
import monochrome from './themes/monochrome.json';
import oceanic from './themes/oceanic.json';
import highContrastDark from './themes/high-contrast-dark.json';
import highContrastLight from './themes/high-contrast-light.json';

/**
 * Every theme shipped with cairn-code.
 *
 * The JSON files are generated by scripts/generate-themes.mjs from compact
 * palettes; see docs/api/theme-api.md for the authoring workflow. Community
 * themes are registered at runtime through `registerTheme`.
 */
const BUILT_IN_THEMES: Theme[] = [
  darkModern as Theme,
  lightModern as Theme,
  midnightViolet as Theme,
  nordic as Theme,
  oceanic as Theme,
  forest as Theme,
  crimson as Theme,
  solarDusk as Theme,
  solarDawn as Theme,
  monochrome as Theme,
  highContrastDark as Theme,
  highContrastLight as Theme
];

const registry = new Map<string, Theme>(BUILT_IN_THEMES.map((theme) => [theme.id, theme]));

/** Returns all known themes in display order. */
export function listThemes(): Theme[] {
  return [...registry.values()];
}

/** Returns one theme by id, or undefined when it is not registered. */
export function getTheme(id: string): Theme | undefined {
  return registry.get(id);
}

/** Adds or replaces a theme, used by the custom theme creator and extensions. */
export function registerTheme(theme: Theme): void {
  registry.set(theme.id, theme);
}

/** Removes a runtime-registered theme. Built-in themes cannot be removed. */
export function unregisterTheme(id: string): boolean {
  if (BUILT_IN_THEMES.some((theme) => theme.id === id)) return false;
  return registry.delete(id);
}

/** The fallback used when a stored theme id no longer resolves. */
export function getFallbackTheme(preferLight = false): Theme {
  const fallback = preferLight ? registry.get('light-modern') : registry.get('dark-modern');
  // BUILT_IN_THEMES always contains both, so this branch is unreachable in
  // practice; it exists so the return type stays non-nullable.
  return fallback ?? (BUILT_IN_THEMES[0] as Theme);
}

export { BUILT_IN_THEMES };
